In [1]:
import numpy as np

In [14]:
A = np.array([[1, 2, 4],
              [7, 5, -2],
              [-2, 1, 3]])

B = np.array([[-1, 0, 3],
              [2, -6, 1],
              [-7, 1, 5]])

C = np.array([[-2, 3],
              [4, 0],
              [7, -1]])

result1 = A + B
result2 = B - A
result3 = A @ C
result4 = A @ B @ C
print(f"Результат сложения матриц A и B: \n{result1}")
print(f"Результат вычитания матриц B и A: \n{result2}")
print(f"Результат умножения матриц A и C: \n{result3}")
print(f"Результат умножения матриц A, B и C: \n{result4}")

Результат сложения матриц A и B: 
[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]
Результат вычитания матриц B и A: 
[[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]]
Результат умножения матриц A и C: 
[[34 -1]
 [-8 23]
 [29 -9]]
Результат умножения матриц A, B и C: 
[[ 193 -100]
 [ -50   35]
 [  92  -61]]


In [15]:
A = np.array([[0, 3, 4],
              [-7, 1, -2],
              [2, -1, 3]])

B = np.array([[1, 2, 4],
              [7, 0, -2],
              [-3, -2, 5]])

C = np.array([[-3, 2],
              [0, 4],
              [-1, 7]])

result1 = A + B
result2 = B - A
result3 = A @ C
result4 = A @ B @ C
print(f"Результат сложения матриц A и B: \n{result1}")
print(f"Результат вычитания матриц B и A: \n{result2}")
print(f"Результат умножения матриц A и C: \n{result3}")
print(f"Результат умножения матриц A, B и C: \n{result4}")

Результат сложения матриц A и B: 
[[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]]
Результат вычитания матриц B и A: 
[[ 1 -1  0]
 [14 -1  0]
 [-5 -1  2]]
Результат умножения матриц A и C: 
[[ -4  40]
 [ 23 -24]
 [ -9  21]]
Результат умножения матриц A, B и C: 
[[ -41   84]
 [  22 -308]
 [  17  139]]


In [16]:
A = np.array([[5, 2, 9],
              [7, 0, -2],
              [-2, 1, 6]])

B = np.array([[1, -2, 1],
              [7, 5, -2],
              [-2, 8, 3]])

C = np.array([[-2, 3],
              [4, 5],
              [0, -1]])

result1 = A + B
result2 = B - A
result3 = A @ C
result4 = A @ B @ C
print(f"Результат сложения матриц A и B: \n{result1}")
print(f"Результат вычитания матриц B и A: \n{result2}")
print(f"Результат умножения матриц A и C: \n{result3}")
print(f"Результат умножения матриц A, B и C: \n{result4}")

Результат сложения матриц A и B: 
[[ 6  0 10]
 [14  5 -4]
 [-4  9  9]]
Результат вычитания матриц B и A: 
[[-4 -4 -8]
 [ 0  5  0]
 [ 0  7 -3]]
Результат умножения матриц A и C: 
[[ -2  16]
 [-14  23]
 [  8  -7]]
Результат умножения матриц A, B и C: 
[[ 286  335]
 [-142 -118]
 [ 242  250]]


In [17]:
A = np.array([[1, -2, 8],
              [7, 5, -2],
              [2, 3, 0]])

B = np.array([[0, 2, 4],
              [1, -3, -2],
              [-2, 1, 3]])

C = np.array([[0, 3],
              [5, -4],
              [7, -1]])

result1 = A + B
result2 = B - A
result3 = A @ C
result4 = A @ B @ C
print(f"Результат сложения матриц A и B: \n{result1}")
print(f"Результат вычитания матриц B и A: \n{result2}")
print(f"Результат умножения матриц A и C: \n{result3}")
print(f"Результат умножения матриц A, B и C: \n{result4}")

Результат сложения матриц A и B: 
[[ 1  0 12]
 [ 8  2 -4]
 [ 0  4  3]]
Результат вычитания матриц B и A: 
[[-1  4 -4]
 [-6 -8  0]
 [-4 -2  3]]
Результат умножения матриц A и C: 
[[46  3]
 [11  3]
 [15 -6]]
Результат умножения матриц A, B и C: 
[[ 304 -150]
 [  69   27]
 [ -11   27]]


In [18]:
A = np.array([[9, 2, 4],
              [7, 5, -5],
              [6, -2, 3]])

B = np.array([[8, 2, 4],
              [0, 1, -3],
              [-2, 1, 6]])

C = np.array([[-2, 0],
              [4, 8],
              [1, -1]])

result1 = A + B
result2 = B - A
result3 = A @ C
result4 = A @ B @ C
print(f"Результат сложения матриц A и B: \n{result1}")
print(f"Результат вычитания матриц B и A: \n{result2}")
print(f"Результат умножения матриц A и C: \n{result3}")
print(f"Результат умножения матриц A, B и C: \n{result4}")

Результат сложения матриц A и B: 
[[17  4  8]
 [ 7  6 -8]
 [ 4 -1  9]]
Результат вычитания матриц B и A: 
[[-1  0  0]
 [-7 -4  2]
 [-8  3  3]]
Результат умножения матриц A и C: 
[[ -6  12]
 [  1  45]
 [-17 -19]]
Результат умножения матриц A, B и C: 
[[ 22 138]
 [-93 129]
 [ 16  56]]


In [32]:
A = np.array([[4, 0, 4, 5],
              [0, 1, 5, 6],
              [-2, 2, 2, 0],
              [1, -5, 1, 3]])

A_inv = np.linalg.inv(A)
det = np.linalg.det(A)
print(f"Определитель: {det:.2f}")
print("Обратная матрица A:")
print(np.round(A_inv, 2))
I = A @ A_inv
print("Проверка единичной матрицы:")
print(np.round(I, 0))

Определитель: 188.00
Обратная матрица A:
[[ 0.26 -0.19 -0.01 -0.04]
 [-0.03  0.15 -0.19 -0.24]
 [ 0.29 -0.34  0.68  0.2 ]
 [-0.23  0.43 -0.53 -0.13]]
Проверка единичной матрицы:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
A = np.array([[5, 1, 3, 0],
              [-3, 0, 5, 2],
              [2, 1, -1, 3],
              [1, 5, 0, 7]])

A_inv = np.linalg.inv(A)
det = np.linalg.det(A)
print(f"Определитель: {det:.2f}")
print("Обратная матрица A:")
print(np.round(A_inv, 2))
I = A @ A_inv
print("Проверка единичной матрицы:")
print(np.round(I, 0))

Определитель: 408.00
Обратная матрица A:
[[ 0.12 -0.04  0.16 -0.06]
 [ 0.08 -0.17 -0.6   0.3 ]
 [ 0.1   0.12 -0.07 -0.01]
 [-0.07  0.12  0.4  -0.07]]
Проверка единичной матрицы:
[[ 1. -0.  0. -0.]
 [ 0.  1.  0. -0.]
 [-0. -0.  1. -0.]
 [ 0. -0.  0.  1.]]


In [33]:
A = np.array([[7, 6, 0, 1],
              [1, 3, 5, 0],
              [0, 1, -2, 4],
              [1, 1, 2, 3]])

A_inv = np.linalg.inv(A)
det = np.linalg.det(A)
print(f"Определитель: {det:.2f}")
print("Обратная матрица A:")
print(np.round(A_inv, 2))
I = A @ A_inv
print("Проверка единичной матрицы:")
print(np.round(I, 0))

Определитель: -288.00
Обратная матрица A:
[[ 0.13 -0.28 -0.32  0.38]
 [ 0.02  0.33  0.35 -0.48]
 [-0.04  0.06 -0.15  0.21]
 [-0.02 -0.06  0.09  0.23]]
Проверка единичной матрицы:
[[ 1.  0. -0. -0.]
 [ 0.  1.  0. -0.]
 [ 0. -0.  1.  0.]
 [-0.  0.  0.  1.]]
